// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgM-8haTaKdxWKbKFwglnk2BCbpN3ubDs',
    appId: '1:963121535055:web:8ac21c861379196818323a',
    messagingSenderId: '963121535055',
    projectId: 'food-ordering-app-a6edb',
    authDomain: 'food-ordering-app-a6edb.firebaseapp.com',
    storageBucket: 'food-ordering-app-a6edb.firebasestorage.app',
    measurementId: 'G-PE402EXEVT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtSDTWRCENcdcZ4pcg6ty_fpVf2cgDfo8',
    appId: '1:963121535055:android:c92502acc46289ac18323a',
    messagingSenderId: '963121535055',
    projectId: 'food-ordering-app-a6edb',
    storageBucket: 'food-ordering-app-a6edb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4BaBmBn9iKivSwImR7DkGDifd7TzdYwo',
    appId: '1:963121535055:ios:b06ecaea642292c018323a',
    messagingSenderId: '963121535055',
    projectId: 'food-ordering-app-a6edb',
    storageBucket: 'food-ordering-app-a6edb.firebasestorage.app',
    iosBundleId: 'com.example.foodOrderApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4BaBmBn9iKivSwImR7DkGDifd7TzdYwo',
    appId: '1:963121535055:ios:b06ecaea642292c018323a',
    messagingSenderId: '963121535055',
    projectId: 'food-ordering-app-a6edb',
    storageBucket: 'food-ordering-app-a6edb.firebasestorage.app',
    iosBundleId: 'com.example.foodOrderApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgM-8haTaKdxWKbKFwglnk2BCbpN3ubDs',
    appId: '1:963121535055:web:f23678938708c17f18323a',
    messagingSenderId: '963121535055',
    projectId: 'food-ordering-app-a6edb',
    authDomain: 'food-ordering-app-a6edb.firebaseapp.com',
    storageBucket: 'food-ordering-app-a6edb.firebasestorage.app',
    measurementId: 'G-XDN1ZHDYX7',
  );

}